/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface BudgetLimit { 'category' : string, 'amount' : number }
export interface Transaction {
  'id' : string,
  'created' : bigint,
  'transactionType' : TransactionType,
  'date' : bigint,
  'description' : string,
  'category' : string,
  'amount' : number,
}
export type TransactionType = { 'expense' : null } |
  { 'income' : null };
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addTransaction' : ActorMethod<[Transaction], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'deleteTransaction' : ActorMethod<[string], boolean>,
  'getAllBudgetLimits' : ActorMethod<[], Array<BudgetLimit>>,
  'getBudgetLimit' : ActorMethod<[string], [] | [number]>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCategories' : ActorMethod<[], Array<string>>,
  'getRecentTransactions' : ActorMethod<[bigint], Array<Transaction>>,
  'getSpendingByCategory' : ActorMethod<
    [bigint, bigint],
    Array<[string, number]>
  >,
  'getTotalBalance' : ActorMethod<[], number>,
  'getTotalExpensesForMonth' : ActorMethod<[bigint, bigint], number>,
  'getTotalIncomeForMonth' : ActorMethod<[bigint, bigint], number>,
  'getTransactions' : ActorMethod<[], Array<Transaction>>,
  'getTransactionsByCategory' : ActorMethod<[string], Array<Transaction>>,
  'getTransactionsByType' : ActorMethod<[TransactionType], Array<Transaction>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'setBudgetLimit' : ActorMethod<[string, number], undefined>,
  'updateTransaction' : ActorMethod<[string, Transaction], boolean>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];