/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const TransactionType = IDL.Variant({
  'expense' : IDL.Null,
  'income' : IDL.Null,
});
export const Transaction = IDL.Record({
  'id' : IDL.Text,
  'created' : IDL.Int,
  'transactionType' : TransactionType,
  'date' : IDL.Int,
  'description' : IDL.Text,
  'category' : IDL.Text,
  'amount' : IDL.Float64,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const BudgetLimit = IDL.Record({
  'category' : IDL.Text,
  'amount' : IDL.Float64,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addTransaction' : IDL.Func([Transaction], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'deleteTransaction' : IDL.Func([IDL.Text], [IDL.Bool], []),
  'getAllBudgetLimits' : IDL.Func([], [IDL.Vec(BudgetLimit)], ['query']),
  'getBudgetLimit' : IDL.Func([IDL.Text], [IDL.Opt(IDL.Float64)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCategories' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
  'getRecentTransactions' : IDL.Func(
      [IDL.Nat],
      [IDL.Vec(Transaction)],
      ['query'],
    ),
  'getSpendingByCategory' : IDL.Func(
      [IDL.Int, IDL.Int],
      [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Float64))],
      ['query'],
    ),
  'getTotalBalance' : IDL.Func([], [IDL.Float64], ['query']),
  'getTotalExpensesForMonth' : IDL.Func(
      [IDL.Int, IDL.Int],
      [IDL.Float64],
      ['query'],
    ),
  'getTotalIncomeForMonth' : IDL.Func(
      [IDL.Int, IDL.Int],
      [IDL.Float64],
      ['query'],
    ),
  'getTransactions' : IDL.Func([], [IDL.Vec(Transaction)], ['query']),
  'getTransactionsByCategory' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(Transaction)],
      ['query'],
    ),
  'getTransactionsByType' : IDL.Func(
      [TransactionType],
      [IDL.Vec(Transaction)],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'setBudgetLimit' : IDL.Func([IDL.Text, IDL.Float64], [], []),
  'updateTransaction' : IDL.Func([IDL.Text, Transaction], [IDL.Bool], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const TransactionType = IDL.Variant({
    'expense' : IDL.Null,
    'income' : IDL.Null,
  });
  const Transaction = IDL.Record({
    'id' : IDL.Text,
    'created' : IDL.Int,
    'transactionType' : TransactionType,
    'date' : IDL.Int,
    'description' : IDL.Text,
    'category' : IDL.Text,
    'amount' : IDL.Float64,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const BudgetLimit = IDL.Record({
    'category' : IDL.Text,
    'amount' : IDL.Float64,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addTransaction' : IDL.Func([Transaction], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'deleteTransaction' : IDL.Func([IDL.Text], [IDL.Bool], []),
    'getAllBudgetLimits' : IDL.Func([], [IDL.Vec(BudgetLimit)], ['query']),
    'getBudgetLimit' : IDL.Func([IDL.Text], [IDL.Opt(IDL.Float64)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCategories' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
    'getRecentTransactions' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(Transaction)],
        ['query'],
      ),
    'getSpendingByCategory' : IDL.Func(
        [IDL.Int, IDL.Int],
        [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Float64))],
        ['query'],
      ),
    'getTotalBalance' : IDL.Func([], [IDL.Float64], ['query']),
    'getTotalExpensesForMonth' : IDL.Func(
        [IDL.Int, IDL.Int],
        [IDL.Float64],
        ['query'],
      ),
    'getTotalIncomeForMonth' : IDL.Func(
        [IDL.Int, IDL.Int],
        [IDL.Float64],
        ['query'],
      ),
    'getTransactions' : IDL.Func([], [IDL.Vec(Transaction)], ['query']),
    'getTransactionsByCategory' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(Transaction)],
        ['query'],
      ),
    'getTransactionsByType' : IDL.Func(
        [TransactionType],
        [IDL.Vec(Transaction)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'setBudgetLimit' : IDL.Func([IDL.Text, IDL.Float64], [], []),
    'updateTransaction' : IDL.Func([IDL.Text, Transaction], [IDL.Bool], []),
  });
};

export const init = ({ IDL }) => { return []; };